### ISSUE TITLE
Configurable restart command

### ISSUE THREAD

**Issue by Eufranio** [ModdedMinecraft/MMCPrefix#3]
I would like that you provide a configurable restart command feature. So, if we have another plugin doing stuff on restart (like I have), your plugin could simply run the command we set.

**Comment by leelawd** [comment]
Could you possibly expand on this? I'm not quite catching what you mean exactly.

Possibly could provide some sort of example?

**Comment by Eufranio** [comment]
In my server, we already have a restart plugin, but it will start the countdown on a command (/restart). I would like to use your plugin along mine, so when the server reaches the time specified in config (6 hours) it runs the command (/reiniciar) and then the server will restart.

**Comment by leelawd** [comment]
I am assuming your meaning this for my MMCReboot plugin? since this is a different issues page for another plugin.

And just so I'm 100% clear on this. The request is as follows:
- My plugin will use its countdown 
- Upon reaching the end of the countdown timer, a command will be sent instead of a restart being performed
- The command will be configurable from the config

is that correct?

**Comment by Eufranio** [comment]
Yes correct, rofl I opened an issue here instead the right page, sorry......

**Comment by leelawd** [comment]
This is in the latest https://github.com/ModdedMinecraft/MMCReboot-Sponge/releases

https://github.com/ModdedMinecraft/MMCReboot-Sponge/commit/f96643468cfb1765af94fd26858401d93ed2b286
